export const LAYER_CONFIG = {
  // === BASIS & GEVOEL ===
  temperature: {
    label: "Temperatuur",
    variable: "t_2m",
    unit: "°C",
    description: "Luchttemperatuur op 2 meter hoogte",
    legendValues: ["-5", "0", "5", "10", "15", "20", "25", "30"],
  },
  dewpoint: {
    label: "Dauwpunt",
    variable: "td_2m",
    unit: "°C",
    description: "Temperatuur waarop lucht verzadigd wordt",
    legendValues: ["-10", "-5", "0", "5", "10", "15", "20"],
  },
  tmax: {
    label: "Max Temperatuur",
    variable: "tmax_2m",
    unit: "°C",
    description: "Maximale luchttemperatuur op 2 meter",
    legendValues: ["0", "5", "10", "15", "20", "25", "30", "35"],
  },
  tmin: {
    label: "Min Temperatuur",
    variable: "tmin_2m",
    unit: "°C",
    description: "Minimale luchttemperatuur op 2 meter",
    legendValues: ["-10", "-5", "0", "5", "10", "15", "20"],
  },
  wind_u: {
    label: "Wind (O-W)",
    variable: "u_10m",
    unit: "m/s",
    description: "Windsnelheid oost-west component op 10m hoogte",
    legendValues: ["-25", "-15", "-5", "0", "5", "15", "25"],
  },
  wind_v: {
    label: "Wind (N-Z)",
    variable: "v_10m",
    unit: "m/s",
    description: "Windsnelheid noord-zuid component op 10m hoogte",
    legendValues: ["-25", "-15", "-5", "0", "5", "15", "25"],
  },
  windgust: {
    label: "Windstoten",
    variable: "vmax_10m",
    unit: "m/s",
    description: "Maximale windstoten op 10 meter hoogte",
    legendValues: ["0", "5", "10", "15", "25", "40"],
  },
  pressure_msl: {
    label: "Luchtdruk (MSL)",
    variable: "pmsl",
    unit: "hPa",
    description: "Oppervlaktedruk herleid naar zeeniveau (isobaren)",
    legendValues: ["970", "990", "1010", "1030", "1050"],
  },
  pressure_surface: {
    label: "Luchtdruk (Oppervlak)",
    variable: "ps",
    unit: "hPa",
    description: "Oppervlaktedruk aan het aardoppervlak",
    legendValues: ["970", "990", "1010", "1030", "1050"],
  },
  weather_code: {
    label: "Weercode",
    variable: "ww",
    unit: "code",
    description: "Actueel weerbeeld (WMO codes)",
    legendValues: ["0", "1", "3", "9", "23", "30"],
  },
  visibility: {
    label: "Zicht",
    variable: "vis",
    unit: "km",
    description: "Horizontaal zicht (zichtafstand)",
    legendValues: ["0", "2", "5", "10", "15", "20"],
  },

  // === NEERSLAG & BUIENRADAR ===
  tot_precip: {
    label: "Totale Neerslag",
    variable: "tot_prec",
    unit: "mm",
    description: "Totale neerslagaccumulatie",
    legendValues: ["0", "1", "5", "10", "20"],
  },
  rain_large: {
    label: "Grootschalige Regen",
    variable: "rain_gsp",
    unit: "mm",
    description: "Grootschalige regenbui",
    legendValues: ["0", "2", "5", "10", "20"],
  },
  snow_large: {
    label: "Grootschalige Sneeuw",
    variable: "snow_gsp",
    unit: "mm",
    description: "Grootschalige sneeuwbui",
    legendValues: ["0", "2", "5", "10", "20"],
  },
  rain_conv: {
    label: "Convectieve Regen",
    variable: "rain_con",
    unit: "mm",
    description: "Convectieve regen (buien)",
    legendValues: ["0", "2", "5", "10", "20"],
  },
  snow_conv: {
    label: "Convectieve Sneeuw",
    variable: "snow_con",
    unit: "mm",
    description: "Convectieve sneeuwbuien",
    legendValues: ["0", "2", "5", "10", "20"],
  },
  graupel_intensity: {
    label: "Graupel Intensiteit",
    variable: "prg_gsp",
    unit: "mm",
    description: "Graupel/hagel intensiteit",
    legendValues: ["0", "1", "2", "5", "10"],
  },
  rain_intensity: {
    label: "Regen Intensiteit",
    variable: "prr_gsp",
    unit: "mm",
    description: "Regen intensiteit",
    legendValues: ["0", "2", "5", "10", "20"],
  },
  snow_intensity: {
    label: "Sneeuw Intensiteit",
    variable: "prs_gsp",
    unit: "mm",
    description: "Sneeuw intensiteit",
    legendValues: ["0", "2", "5", "10", "20"],
  },
  radar_composite: {
    label: "Radarreflectiviteit (BUIENRADAR!)",
    variable: "dbz_cmax",
    unit: "dBZ",
    description: "Composite/maximale radarreflectiviteit - de bekende buienradar",
    legendValues: ["-10", "5", "15", "25", "35", "45", "60"],
  },
  radar_850: {
    label: "Radar op 850 hPa",
    variable: "dbz_850",
    unit: "dBZ",
    description: "Radarreflectiviteit op 850 hPa hoogte",
    legendValues: ["-10", "5", "15", "25", "35", "45", "60"],
  },
  graupel: {
    label: "Graupel/Hagel",
    variable: "grau_gsp",
    unit: "mm",
    description: "Graupel/hagel aan het oppervlak",
    legendValues: ["0", "1", "2", "5", "10"],
  },
  runoff_ground: {
    label: "Grondwater Afstroming",
    variable: "runoff_g",
    unit: "mm",
    description: "Grondwaterafstroming van neerslag",
    legendValues: ["0", "1", "2", "5", "10"],
  },
  runoff_surface: {
    label: "Oppervlakte Afstroming",
    variable: "runoff_s",
    unit: "mm",
    description: "Oppervlakteafstroming van neerslag",
    legendValues: ["0", "1", "2", "5", "10"],
  },

  // === BEWOLKING & WOLKENOPBOUW ===
  clouds_total: {
    label: "Totale Bewolking",
    variable: "clct",
    unit: "%",
    description: "Totale wolkenbedekkking",
    legendValues: ["0", "20", "40", "60", "80", "100"],
  },
  clouds_mod: {
    label: "Gemodificeerde Bewolking",
    variable: "clct_mod",
    unit: "%",
    description: "Gemodificeerde totale bewolking",
    legendValues: ["0", "20", "40", "60", "80", "100"],
  },
  clouds_low: {
    label: "Lage Wolken",
    variable: "clcl",
    unit: "%",
    description: "Lage wolken (< 2km)",
    legendValues: ["0", "20", "40", "60", "80", "100"],
  },
  clouds_mid: {
    label: "Middelbare Wolken",
    variable: "clcm",
    unit: "%",
    description: "Middelbare wolken (2-6km)",
    legendValues: ["0", "20", "40", "60", "80", "100"],
  },
  clouds_high: {
    label: "Hoge Wolken",
    variable: "clch",
    unit: "%",
    description: "Hoge wolken (> 6km)",
    legendValues: ["0", "20", "40", "60", "80", "100"],
  },
  ceiling_height: {
    label: "Wolkenbasis Hoogte",
    variable: "ceiling",
    unit: "m",
    description: "Wolkenbasis / plafondhoogte",
    legendValues: ["0", "500", "1000", "2000", "3000", "5000"],
  },
  cloud_depth: {
    label: "Wolkdikte",
    variable: "cldepth",
    unit: "m",
    description: "Dikte van de wolkenlaag",
    legendValues: ["0", "500", "1000", "2000", "3000"],
  },
  sc_base: {
    label: "Stratocumulus Basis",
    variable: "hbas_sc",
    unit: "m",
    description: "Basis van stratocumulus/onderste wolken",
    legendValues: ["0", "500", "1000", "1500", "2000"],
  },
  sc_top: {
    label: "Stratocumulus Top",
    variable: "htop_sc",
    unit: "m",
    description: "Top van stratocumulus/onderste wolken",
    legendValues: ["500", "1000", "1500", "2000", "3000"],
  },
  convection_top: {
    label: "Diepe Convectie Top",
    variable: "htop_dc",
    unit: "m",
    description: "Top van diepe convectieve wolken (onweerswolken)",
    legendValues: ["3000", "5000", "8000", "12000", "15000"],
  },

  // === ONWEER & NOODWEER ===
  cape: {
    label: "CAPE",
    variable: "cape_ml",
    unit: "J/kg",
    description: "Convectieve potentiële energie (mixed-layer)",
    legendValues: ["0", "500", "1000", "2000", "3500"],
  },
  cin: {
    label: "Convectieve Inhibitie",
    variable: "cin_ml",
    unit: "J/kg",
    description: "Convective Inhibition - de 'deksel' op buien",
    legendValues: ["0", "50", "100", "200", "300"],
  },
  lpi: {
    label: "Bliksemkans Index",
    variable: "lpi",
    unit: "index",
    description: "Lightning Potential Index - bliksemwaarschijnlijkheid",
    legendValues: ["0", "25", "50", "75", "100", "150"],
  },
  lpi_max: {
    label: "Max Bliksemkans",
    variable: "lpi_max",
    unit: "index",
    description: "Maximale Lightning Potential Index",
    legendValues: ["0", "25", "50", "75", "100", "150"],
  },
  uh_max: {
    label: "Max Updraft Helicity",
    variable: "uh_max",
    unit: "m²/s²",
    description: "Maximale updraft helicity - rotatie in buien",
    legendValues: ["0", "50", "100", "200", "300"],
  },
  uh_low: {
    label: "Updraft Helicity (Laag)",
    variable: "uh_max_low",
    unit: "m²/s²",
    description: "Updraft helicity op lage hoogte",
    legendValues: ["0", "50", "100", "200", "300"],
  },
  uh_mid: {
    label: "Updraft Helicity (Midden)",
    variable: "uh_max_med",
    unit: "m²/s²",
    description: "Updraft helicity op middelbare hoogte",
    legendValues: ["0", "50", "100", "200", "300"],
  },
  echo_top: {
    label: "Echo Top Hoogte",
    variable: "echotop",
    unit: "m",
    description: "Hoogte van de hoogste radarecho",
    legendValues: ["2000", "5000", "10000", "15000", "20000"],
  },

  // === LUCHTMASSA & VOCHT ===
  humidity_general: {
    label: "Relatieve Vochtigheid",
    variable: "relhum",
    unit: "%",
    description: "Relatieve luchtvochtigheid (algemeen)",
    legendValues: ["0", "20", "40", "60", "80", "100"],
  },
  humidity_2m: {
    label: "Relatieve Vochtigheid 2m",
    variable: "relhum_2m",
    unit: "%",
    description: "Relatieve luchtvochtigheid op 2 meter hoogte",
    legendValues: ["0", "20", "40", "60", "80", "100"],
  },
  qv_surface: {
    label: "Specifieke Vochtigheid",
    variable: "qv_s",
    unit: "g/kg",
    description: "Specifieke vochtigheid aan oppervlak",
    legendValues: ["0", "5", "10", "15", "20"],
  },
  tqv_column: {
    label: "Totale Waterdamp Kolom",
    variable: "tqv",
    unit: "kg/m²",
    description: "Totale hoeveelheid waterdamp in luchtkolom",
    legendValues: ["10", "20", "30", "40", "50"],
  },
  water_column: {
    label: "Totaal Watergehalte",
    variable: "twater",
    unit: "kg/m²",
    description: "Totaal geïntegreerd watergehalte (water+ijs+damp)",
    legendValues: ["0", "10", "20", "40", "80"],
  },
  cloud_water: {
    label: "Wolkwater Kolom",
    variable: "tqc",
    unit: "kg/m²",
    description: "Geïntegreerde kolom wolkwater",
    legendValues: ["0", "0.05", "0.1", "0.2", "0.5"],
  },
  graupel_col: {
    label: "Graupel Kolom",
    variable: "tqg",
    unit: "kg/m²",
    description: "Geïntegreerde kolom graupel",
    legendValues: ["0", "0.01", "0.05", "0.1", "0.2"],
  },
  ice_col: {
    label: "Ijs Kolom",
    variable: "tqi",
    unit: "kg/m²",
    description: "Geïntegreerde kolom ijs",
    legendValues: ["0", "0.1", "0.2", "0.5", "1.0"],
  },
  rain_col: {
    label: "Regen Kolom",
    variable: "tqr",
    unit: "kg/m²",
    description: "Geïntegreerde kolom regen",
    legendValues: ["0", "0.05", "0.1", "0.2", "0.5"],
  },
  snow_col: {
    label: "Sneeuw Kolom",
    variable: "tqs",
    unit: "kg/m²",
    description: "Geïntegreerde kolom sneeuw",
    legendValues: ["0", "0.05", "0.1", "0.2", "0.5"],
  },

  // === SPECIALISTISCHE EXTRA'S ===
  freezing_level: {
    label: "0°C Isotherm Hoogte",
    variable: "hzerocl",
    unit: "m",
    description: "Hoogte van het vriespunt (0°C-grens)",
    legendValues: ["500", "1000", "2000", "3000", "4000", "5000"],
  },
  snow_coverage: {
    label: "Sneeuwbedekkking",
    variable: "snowc",
    unit: "%",
    description: "Sneeuwbedekkingsgraad op grond",
    legendValues: ["0", "20", "40", "60", "80", "100"],
  },
  snow_limit: {
    label: "Sneeuwvalgrens",
    variable: "snowlmt",
    unit: "m",
    description: "Sneeuwvalgrens - hoogte waar neerslag sneeuw wordt",
    legendValues: ["500", "1000", "1500", "2000", "3000"],
  },
  lake_water_temp: {
    label: "Meerwater Temperatuur",
    variable: "t_wml_lk",
    unit: "°C",
    description: "Watertemperatuur gemengde bovenlaag meren",
    legendValues: ["0", "5", "10", "15", "20", "25"],
  },
  roughness: {
    label: "Ruwheidslengte",
    variable: "z0",
    unit: "m",
    description: "Terreinruwheidslengte (voor lokale wrijving op wind)",
    legendValues: ["0.001", "0.01", "0.1", "0.5", "1.0"],
  },
};
